# Generated by Django 3.1 on 2022-09-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic',
            new_name='picture',
        ),
    ]
